version: "3.7"
services:
  fast-api:
    build:
      context: ./docker-images-fastapi
      dockerfile: Dockerfile
    environment:
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: mysql-db
      DATABASE_DB_NAME: database
    ports:
      - 3032:80
    volumes:
      - ./docker-images-fastapi/app:/app
  react-client:
    build:
      context: ./docker-images-react
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./docker-images-react:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:3000
    environment:
      # バックエンドAPIへのエンドポイント
      REACT_APP_BACKEND_API_ENDPOINT: ""
    stdin_open: true
  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ="Asia/Tokyo"
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --skip-character-set-client-handshake --default_authentication_plugin=mysql_native_password
    volumes:
      - ./database:/docker-entrypoint-initdb.d # docker-entrypoint-initdb.d内のスクリプトは起動時に1度だけ実行される
  test:
    build:
      context: ./docker-images-fastapi
      dockerfile: Dockerfile-test
    volumes:
      - ./docker-images-fastapi/app:/app
