# build stage
FROM public.ecr.aws/docker/library/node:16-stretch-slim as build
WORKDIR /usr/src/app

COPY ./docker-images-react ./
COPY ./codebuild/frontend/package.json ./package.json
RUN yarn install
RUN yarn build

# deploy stage
FROM public.ecr.aws/nginx/nginx:1.23-alpine
COPY --from=build /usr/src/app/build /var/www
COPY ./codebuild/frontend/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
WORKDIR /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]